### PR TITLE
update and upload chinese translation

### PR DESCRIPTION
**Pull request by Lzw104522773**
update and upload chinese translation

### CODE REVIEW

**Comment by Lzw104522773** [comment]
Due to the language encoding conversion during the installation process, the UTF-8 encoded Chinese text will become garbled. Therefore, the UTF-8 encoded Chinese text will be saved as ANSI encoding to avoid text garbled due to encoding conversion.

**Comment by ALIENQuake** [comment]
@Lzw104522773 Who is the author?

**Comment by Lzw104522773** [comment]
I'm not sure, so I didn't specify the translator

**Comment by ALIENQuake** [comment]
@Lzw104522773 Sorry to bother you again. Simply changing `~` to `"` is not enough for ANSI encoding. I converted the utf8 to gb2312 since that's what bg1npc mod uses. Files that appear on GitHub web interface are automatically transcoded into utf8 so it's not the actual representation of the actual character bytes.

Please test those changes from master branch and report back.

**Pull request merged**
